[CQT-66] Create examples for ABA decomposer
QuTech-Delft/OpenSquirrel pull request #264
Opened 2024-07-24 15:36 UTC by juanboschero

- Create documentation for all decomposition strategies 
-  Include  example usage 
- Create corresponding tests

2024-07-25 14:05 UTC, S-Linde requested changes
Before I go into a more detailed review I want to mention some more high level stuff. The tutorial is very detailed and contains a lot of math. This level of explanation is great, but it removes some of the flow of your text. My suggestion would be to keep the mathematical explanation in the notebook, but put it at the end and refer to it in the text.

Then you can explain on a high level what a ABA decomposer does and then dive straight into the examples, which is what I would expect from a tutorial. The interested reader is then referred to the math further below.

2024-07-26 05:49 UTC, juanboschero commented on pyproject.toml
> +jupyter = "^1.0.0"
Oh nice catch! It should be with sympy in the optionals deps

2024-07-29 14:01 UTC, S-Linde reviewed
Looking very nice! This structure is much more digestible for me. Really like the ascii-art circuits! (Might be nice to have that for the circuits in the examples as well?)

2024-08-05 10:38 UTC, juanboschero commented on example/tutorials/decompositions.ipynb
> +    "circuit.decompose(decomposer = ZYZDecomposer())\n",
Do you know how to add this in the `pyproject.toml`?

2024-08-05 10:59 UTC, rturrado reviewed
They say naming is one of the most difficult things when programming.

But decent, consistent names gives us a hint that there is some structure in the code.

Non descriptive, inconsistent names could indicate the opposite. Here, that's a false negative, because the tests are actually well structured.

So I'm just missing some better names.

2024-08-05 10:59 UTC, rturrado commented on test/example/tutorials/test_decompositions.py
> +    def test_sympy_disp(self):
What is `disp`? I would change the name into  `test_simpy_<whatever full word>`.

2024-08-05 10:59 UTC, rturrado commented on test/example/tutorials/test_decompositions.py
> +    def test_builder_ABA(self):
What does `builder_ABA` means here? What is being tested? The builder? An input circuit for the ABA decomposer?

I would suggest to not use uppercase for function names.

2024-08-05 10:59 UTC, rturrado commented on test/example/tutorials/test_decompositions.py
> +    def test_builder_and_mckay(self):
Test this and that sounds a bit like a code smell. Maybe just `tests_mckay_decomposer`?

2024-08-05 10:59 UTC, rturrado commented on test/example/tutorials/test_decompositions.py
> +    def test_builder_and_cnot(self):
Same here: `test_cnot_decomposer`?

2024-08-05 11:03 UTC, rturrado commented
It seems:
1. The branch name has nothing to do with the task name.
2. The goal Jira task, to which name I've just set the name of this PR, has been updated from 'Add examples for ABA decomposer' to 'Add examples for all the decompositions'.

2024-08-05 11:04 UTC, rturrado commented on test/example/tutorials/test_decompositions.py
> +    def test_builder_ABA(self):
According to the names of the other tests, this should be `test_aba_decomposer`:

```suggestion
    def test_aba_decomposer(self):
```

2024-08-05 11:05 UTC, rturrado commented on test/example/tutorials/test_decompositions.py
> +    def test_builder_and_mckay(self):
```suggestion
    def test_mckay_decomposer(self):
```

2024-08-05 11:09 UTC, rturrado commented on test/example/tutorials/test_decompositions.py
> +    def test_sympy_disp(self):
```suggestion
    def test_sympy_output(self):
```

2024-08-05 11:09 UTC, rturrado commented on test/example/tutorials/test_decompositions.py
> +    def test_sympy_disp(self):
Why would we test sympy code?

2024-08-05 15:06 UTC, rturrado commented on test/example/tutorials/test_decompositions.py
> +    def test_aba_decomposer_builder_to_circuit(self):
```suggestion
    def test_aba_decomposer_input_circuit_creation(self):
    """This test uses the `CircuitBuilder` to build a circuit that serves as input to the ABA decomposer."""
```

2024-08-05 15:26 UTC, juanboschero commented on test/example/tutorials/test_decompositions.py
> +        assert str(rhs) == rhs_string
It is part of the Jupyter example, if Sympy updates or becomes incompatible with newer dependencies then we will have to know.

2024-08-05 15:30 UTC, rturrado commented on test/example/tutorials/test_decompositions.py
> +        assert str(rhs) == rhs_string
Fair enough!

2024-08-06 05:19 UTC, S-Linde approved these changes

2024-08-06 08:46 UTC, rturrado approved these changes

2024-08-06 10:25 UTC, S-Linde approved these changes

2024-08-08 15:20 UTC, rturrado commented on example/README.md
> +`Jupyter` and `sympy` are required to access the notebooks. These can be installed all at once by running.
```suggestion
`Jupyter` and `sympy` are required to access the notebooks. These can be installed all at once by running:
```

2024-08-08 15:20 UTC, rturrado commented on example/README.md
> +To open the `Jupyter` notebooks, one can run,
```suggestion
To open the `Jupyter` notebooks, one can run
```

2024-08-08 15:20 UTC, rturrado commented on example/README.md
> +```
```suggestion
Alternatively, one can install both packages manually:

```
pip install jupyter sympy
```
```

2024-08-08 15:24 UTC, rturrado commented on example/README.md
> +Alternatively, one can install both packages manually. Installing `Jupyter` using pip can be done by executing,
```suggestion
Alternatively, one can install both packages manually:
```

2024-08-08 15:24 UTC, rturrado commented on example/README.md
> +pip install jupyter
```suggestion
pip install jupyter sympy
```

2024-08-08 15:24 UTC, rturrado commented on example/README.md
> +```
```suggestion
```

2024-08-09 12:14 UTC, elenbaasc approved these changes

2024-08-09 12:19 UTC, merged