#245: support the in operator for RegisterManager and CircuitBuilder
QuTech-Delft/OpenSquirrel pull request #312
Opened 2024-09-02 08:47 UTC by arcturusannamalai

- implement __contains__ method

2024-09-03 09:28 UTC, rturrado commented
@arcturusannamalai Can you please add some tests for this work? Thanks!

2024-09-05 00:43 UTC, arcturusannamalai commented
need a bit more time; will do!

2024-09-07 19:14 UTC, arcturusannamalai commented
done @rturrado

2024-09-10 08:49 UTC, rturrado commented on opensquirrel/circuit.py
> +        return any([qubit in stmt.get_qubit_operands()  for stmt in self.ir.statements])
```suggestion
        return any([qubit in statement.get_qubit_operands()  for statement in self.ir.statements])
```

2024-09-10 08:49 UTC, rturrado commented on opensquirrel/circuit_builder.py
> +        return any([qubit in stmt.get_qubit_operands()  for stmt in self.ir.statements])
```suggestion
        return any([qubit in statement.get_qubit_operands()  for statement in self.ir.statements])
```

2024-09-10 08:51 UTC, rturrado requested changes
Just some minor aesthetic changes.

2024-09-10 08:51 UTC, rturrado commented on test/test_circuit_builder.py
> +        assert Qubit(0) in circuit
```suggestion
        assert Qubit(0) in circuit
        assert not Qubit(1) in builder
```

2024-09-12 11:08 UTC, rturrado commented
@arcturusannamalai It would be worth checking where in the code it is now convenient to use the `in` operator.

Also, please make sure you run the requested tests and linters locally before committing. You can check what to run at the [Contributing](https://github.com/QuTech-Delft/OpenSquirrel/blob/develop/CONTRIBUTING.md#before-creating-the-pull-request) guide.

Thanks!

2024-09-20 07:14 UTC, arcturusannamalai commented
@rturrado - please check my latest attempt :)

2024-09-20 18:28 UTC, rturrado commented
> @rturrado - please check my latest attempt :)

I'm sorry @arcturusannamalai, but could you please explain what the latest commit has to do with the purpose of this PR?

2024-09-21 05:45 UTC, arcturusannamalai commented
> > @rturrado - please check my latest attempt :)
> 
> I'm sorry @arcturusannamalai, but could you please explain what the latest commit has to do with the purpose of this PR?

I added code annotations etc. to pass the criteria in your project post-commit checks. It keeps logic and a new unit-test added for the test intact.

2024-09-23 09:30 UTC, rturrado commented
> I added code annotations etc. to pass the criteria in your project post-commit checks. It keeps logic and a new unit-test added for the test intact.

Sorry, but that `force-pushed the ma-245 branch` contains a lot of changes I didn't understand.

Anyway, you keep missing running the static analysis tools.

2024-12-09 09:12 UTC, closed without merging