Cqt 115 pep8 naming
QuTech-Delft/OpenSquirrel pull request #369
Opened 2024-10-30 11:16 UTC by GuyPuts

Implements PEP8 styling convention, except for function names

2024-11-01 09:41 UTC, elenbaasc commented
Hi Guy, thanks for looking at this.

Note that the pep8-naming option needs to be uncommented in the options of `[tool.ruff.lint]` in `pyproject.toml`, and then ruff needs to be run again (`poetry run ruff check`) to see if everything conforms to the pep8 naming standard.

To ignore pep8 naming (for instance for the gate names)  you can add the `noqa` (no quality assurance) directive followed by the type (code) of ruff error to ignore, e.g.,
`def H(q: QubitLike) -> BlochSphereRotation:  # noqa: N802`
Note that there are two spaces before the `#` and one space after (otherwise ruff format will complain) and that you need to  run ruff to determine the codes (above is N802, to ignore _Function names that should be lowercase_.)

2024-11-01 10:28 UTC, juanboschero submitted a review, later dismissed

2024-11-05 13:24 UTC, juanboschero requested changes

2024-11-05 13:24 UTC, juanboschero commented on opensquirrel/exporter/quantify_scheduler_exporter.py
> +        # exporter test fail.
```suggestion
        # exporter test to fail.
```

2024-11-06 15:45 UTC, GuyPuts commented on opensquirrel/exporter/quantify_scheduler_exporter.py
> +        # exporter test fail.
This has been fixed :)

2024-11-07 09:20 UTC, juanboschero approved these changes

2024-11-07 09:23 UTC, merged